import { useState } from "react";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Button } from "@/components/ui/button";
import { NearbyDoctors } from "@/components/health/NearbyDoctors";
import { HealthDisclaimer } from "@/components/health/HealthDisclaimer";
import { PCOSAssessmentForm } from "@/components/health/PCOSAssessmentForm";
import { PCOSResultsDisplay } from "@/components/health/PCOSResultsDisplay";
import { EducationCard } from "@/components/health/EducationCard";

import { 
  Activity, 
  ArrowRight,
  Sparkles,
  ArrowLeft,
  AlertCircle,
  Heart,
  Scale,
  Droplets,
  Baby,
  Stethoscope,
  Brain,
  Loader2
} from "lucide-react";
import { motion } from "framer-motion";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "@/hooks/use-toast";
import { predictPCOSFromAPI, PCOSInputData, PCOSResult, MLPredictionMeta } from "@/lib/ml-predictions";

type Step = "education" | "assessment" | "results" | "doctors";

const stepLabels = ["Learn", "Assess", "Results", "Consult"];

const PCOSModule = () => {
  const { user } = useAuth();
  const [currentStep, setCurrentStep] = useState<Step>("education");
  const [pcosResult, setPcosResult] = useState<PCOSResult | null>(null);
  const [predictionMeta, setPredictionMeta] = useState<MLPredictionMeta | null>(null);
  const [comparisonMessage, setComparisonMessage] = useState<string | null>(null);

  const [analyzing, setAnalyzing] = useState(false);
  const [saving, setSaving] = useState(false);

  const handleAssessmentSubmit = async (data: PCOSInputData) => {
  setAnalyzing(true);

  try {
    const { _meta, ...result } = await predictPCOSFromAPI(data);

    setPcosResult(result);
    setPredictionMeta(_meta);
    setCurrentStep("results");
    // 🔍 Fetch last assessment for comparison
if (user) {
  const { data: previousAssessments } = await supabase
    .from("health_assessments")
    .select("risk_score, created_at")
    .eq("user_id", user.id)
    .eq("assessment_type", "pcos")
    .order("created_at", { ascending: false })
    .limit(1);

  if (previousAssessments && previousAssessments.length > 0) {
    const lastRisk = Number(previousAssessments[0].risk_score);
    const currentRisk = result.riskPercentage;
    const difference = lastRisk - currentRisk;

    if (difference > 0) {
      setComparisonMessage(
        `🎉 Your risk reduced by ${difference.toFixed(1)}% since last assessment. Keep going!`
      );
    } else if (difference < 0) {
      setComparisonMessage(
        `⚠️ Your risk increased by ${Math.abs(difference).toFixed(1)}%. Consider improving lifestyle habits.`
      );
    } else {
      setComparisonMessage(
        `ℹ️ Your risk remains the same as your last assessment.`
      );
    }
  }
}


    if (_meta.usedAPI) {
      toast({
        title: "ML Model Analysis Complete",
        description: "Results generated by our trained ML model. 🧠",
      });
    } else {
      toast({
        title: "Local Analysis Complete",
        description: _meta.error || "Used built-in scoring logic.",
      });
    }

    if (user) {
      setSaving(true);

      try {
        const { error } = await supabase
          .from("health_assessments")
          .insert({
            user_id: user.id,

            // ✅ FIXED HERE
            assessment_type: "pcos",

            risk_score: result.riskPercentage,

            // if severity is "none", convert to "low"
            risk_category:
  result.severity.toLowerCase() === "none"
    ? "low"
    : result.severity.toLowerCase(),


            responses: data as any,
            recommendations: result.recommendations as any,
          });

        if (error) throw error;

        toast({
          title: "Assessment saved",
          description:
            "Your PCOS assessment results have been saved.",
        });
      } catch (error) {
        console.error("Failed to save assessment:", error);

        toast({
          title: "Error",
          description:
            "Failed to save assessment. Results are still displayed.",
          variant: "destructive",
        });
      } finally {
        setSaving(false);
      }
    }
  } catch (error) {
    console.error("Assessment failed:", error);

    toast({
      title: "Error",
      description: "Assessment failed. Please try again.",
      variant: "destructive",
    });
  } finally {
    setAnalyzing(false);
  }
};


  const restartAssessment = () => {
    setCurrentStep("education");
    setPcosResult(null);
  };

  const currentStepIndex = ["education", "assessment", "results", "doctors"].indexOf(currentStep);

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-24 pb-16">
        <div className="container mx-auto px-4 max-w-4xl">
          {/* Improved Progress Indicator */}
          <div className="mb-10">
            <div className="flex items-center justify-between mb-2">
              {stepLabels.map((label, i) => (
                <div key={label} className="flex flex-col items-center flex-1">
                  <motion.div
                    initial={{ scale: 0.8 }}
                    animate={{ scale: currentStepIndex === i ? 1.1 : 1 }}
                    className={`w-10 h-10 md:w-12 md:h-12 rounded-full flex items-center justify-center text-sm font-bold transition-all duration-300 ${
                      currentStepIndex === i 
                        ? "bg-accent text-accent-foreground shadow-lg shadow-accent/30" 
                        : currentStepIndex > i
                        ? "bg-teal text-teal-foreground"
                        : "bg-muted text-muted-foreground"
                    }`}
                  >
                    {currentStepIndex > i ? "✓" : i + 1}
                  </motion.div>
                  <span className={`text-xs mt-2 font-medium ${
                    currentStepIndex === i ? "text-accent" : "text-muted-foreground"
                  }`}>
                    {label}
                  </span>
                </div>
              ))}
            </div>
            <div className="relative h-1 bg-muted rounded-full mt-4">
              <motion.div
                initial={{ width: "0%" }}
                animate={{ width: `${(currentStepIndex / 3) * 100}%` }}
                className="absolute h-full bg-gradient-to-r from-accent to-teal rounded-full"
                transition={{ duration: 0.5 }}
              />
            </div>
          </div>

          {/* Education Step - Improved Visual Layout */}
          {currentStep === "education" && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="space-y-8"
            >
              {/* Hero Section */}
              <div className="text-center">
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ type: "spring", duration: 0.5 }}
                  className="w-24 h-24 rounded-3xl bg-gradient-to-br from-accent/30 to-primary/30 flex items-center justify-center mx-auto mb-6"
                >
                  <Activity className="w-12 h-12 text-accent" />
                </motion.div>
                <h1 className="font-heading text-3xl md:text-4xl font-bold text-foreground mb-4">
                  Understanding PCOS
                </h1>
                <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
                  Polycystic Ovary Syndrome affects <span className="text-accent font-semibold">1 in 10 women</span>. 
                  Learn about symptoms, risk factors, and get a personalized assessment.
                </p>
              </div>

              {/* Quick Stats Visual */}
              <div className="grid grid-cols-3 gap-4">
                <motion.div
                  initial={{ y: 20, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  transition={{ delay: 0.1 }}
                  className="glass-card rounded-xl p-4 text-center"
                >
                  <div className="text-3xl font-bold text-accent">10%</div>
                  <div className="text-xs text-muted-foreground">Women Affected</div>
                </motion.div>
                <motion.div
                  initial={{ y: 20, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  transition={{ delay: 0.2 }}
                  className="glass-card rounded-xl p-4 text-center"
                >
                  <div className="text-3xl font-bold text-primary">15+</div>
                  <div className="text-xs text-muted-foreground">Symptoms Analyzed</div>
                </motion.div>
                <motion.div
                  initial={{ y: 20, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  transition={{ delay: 0.3 }}
                  className="glass-card rounded-xl p-4 text-center"
                >
                  <div className="text-3xl font-bold text-teal">ML</div>
                  <div className="text-xs text-muted-foreground">Powered Analysis</div>
                </motion.div>
              </div>

              {/* Education Cards */}
              <div className="space-y-4">
                <EducationCard
                  icon={AlertCircle}
                  title="What is PCOS?"
                  description="A hormonal disorder where ovaries produce excess androgens, affecting ovulation and causing various symptoms. It's one of the leading causes of infertility."
                  color="accent"
                  delay={0.1}
                />
                
                <EducationCard
                  icon={Droplets}
                  title="Common Symptoms"
                  description=""
                  items={[
                    "Irregular or missed periods",
                    "Excess hair growth (hirsutism)",
                    "Acne and oily skin",
                    "Weight gain, especially around waist",
                    "Hair thinning on scalp",
                    "Difficulty getting pregnant"
                  ]}
                  color="primary"
                  delay={0.2}
                />
                
                <EducationCard
                  icon={Scale}
                  title="Risk Factors"
                  description=""
                  items={[
                    "Family history of PCOS",
                    "Insulin resistance or Type 2 diabetes",
                    "Obesity or excess weight",
                    "Early puberty (before age 8)"
                  ]}
                  color="teal"
                  delay={0.3}
                />
              </div>

              {/* How It Works Visual */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4 }}
                className="glass-card rounded-2xl p-6 border border-accent/30"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-accent/20 flex items-center justify-center">
                    <Brain className="w-5 h-5 text-accent" />
                  </div>
                  <h3 className="font-heading text-lg font-semibold text-foreground">How Our ML Assessment Works</h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {[
                    { step: 1, title: "Input Data", desc: "Answer 15 health questions" },
                    { step: 2, title: "ML Analysis", desc: "Random Forest + XGBoost ensemble" },
                    { step: 3, title: "Get Results", desc: "Personalized risk assessment" },
                  ].map((item, i) => (
                    <div key={i} className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-accent text-accent-foreground flex items-center justify-center text-sm font-bold">
                        {item.step}
                      </div>
                      <div>
                        <div className="font-medium text-foreground text-sm">{item.title}</div>
                        <div className="text-xs text-muted-foreground">{item.desc}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </motion.div>

              <HealthDisclaimer />

              <div className="text-center">
                <Button size="lg" onClick={() => setCurrentStep("assessment")} className="group text-lg px-8">
                  <Sparkles className="w-5 h-5 mr-2" />
                  Start Assessment
                  <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
                </Button>
              </div>
            </motion.div>
          )}

          {/* Assessment Step */}
          {currentStep === "assessment" && !analyzing && (
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
            >
              <div className="text-center mb-8">
                <h1 className="font-heading text-2xl md:text-3xl font-bold text-foreground mb-2">
                  PCOS Risk Assessment
                </h1>
                <p className="text-muted-foreground">
                  Answer honestly for accurate results • Takes ~3 minutes
                </p>
              </div>

              <PCOSAssessmentForm onSubmit={handleAssessmentSubmit} />

              <div className="text-center mt-6">
                <Button variant="ghost" onClick={() => setCurrentStep("education")}>
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Education
                </Button>
              </div>
            </motion.div>
          )}

          {/* Analyzing Overlay */}
          {analyzing && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex flex-col items-center justify-center py-20"
            >
              <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-accent/30 to-primary/30 flex items-center justify-center mb-6">
                <Loader2 className="w-10 h-10 text-accent animate-spin" />
              </div>
              <h2 className="font-heading text-2xl font-bold text-foreground mb-2">
                Analyzing with ML Model...
              </h2>
              <p className="text-muted-foreground text-sm max-w-sm text-center">
                Running your data through our trained Random Forest + XGBoost ensemble model
              </p>
              <div className="flex gap-1 mt-6">
                {[0, 1, 2].map(i => (
                  <motion.div
                    key={i}
                    className="w-3 h-3 rounded-full bg-accent"
                    animate={{ scale: [1, 1.3, 1], opacity: [0.5, 1, 0.5] }}
                    transition={{ duration: 1, repeat: Infinity, delay: i * 0.2 }}
                  />
                ))}
              </div>
            </motion.div>
          )}

          {/* Results Step */}
          {currentStep === "results" && pcosResult && (
            <div>
              {predictionMeta && (
                <motion.div
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`mb-4 flex items-center justify-center gap-2 px-4 py-2 rounded-full text-xs font-medium w-fit mx-auto ${
                    predictionMeta.usedAPI 
                      ? "bg-teal/20 text-teal border border-teal/30" 
                      : "bg-muted text-muted-foreground border border-border"
                  }`}
                >
                  <Brain className="w-3.5 h-3.5" />
                  {predictionMeta.usedAPI ? "🧠 ML Model Prediction" : "📊 Local Analysis (Fallback)"}
                </motion.div>
              )}
              {comparisonMessage && (
  <div className="mb-4 p-4 rounded-xl bg-accent/10 border border-accent/20 text-center text-sm font-medium">
    {comparisonMessage}
  </div>
)}

              <PCOSResultsDisplay 
                result={pcosResult}
                onFindDoctors={() => setCurrentStep("doctors")}
                onRestart={restartAssessment}
              />
            </div>
          )}

          {/* Doctors Step */}
          {currentStep === "doctors" && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
            >
              <div className="text-center mb-10">
                <div className="w-16 h-16 rounded-2xl bg-primary/20 flex items-center justify-center mx-auto mb-4">
                  <Stethoscope className="w-8 h-8 text-primary" />
                </div>
                <h1 className="font-heading text-3xl md:text-4xl font-bold text-foreground mb-4">
                  Find PCOS Specialists
                </h1>
                <p className="text-muted-foreground">
                  Connect with qualified gynecologists and endocrinologists near you
                </p>
              </div>

              <NearbyDoctors specialty="Gynecologist" />

              <div className="flex flex-col sm:flex-row gap-4 justify-center mt-10">
                <Button variant="outline" onClick={() => setCurrentStep("results")}>
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Results
                </Button>
                <Button variant="outline" onClick={restartAssessment}>
                  Take Assessment Again
                </Button>
              </div>
            </motion.div>
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PCOSModule;
